CREATE TABLE  "CLASS_TYPE" (	
    "ID" 			NUMBER 		NOT NULL ENABLE, 
	"CLASS_TYPE" 	NCHAR(50) 	NOT NULL ENABLE, 
	 CONSTRAINT "CLASS_TYPE_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE, 
	 CONSTRAINT "CLASS_TYPE_CON" CHECK ( "CLASS_TYPE" in ('lecture room', 'laboratory', 'computer class', 'projection room')) ENABLE
   )
/

CREATE TABLE  "CLASSROOM" (	
    "CLUSSROOM_NUMBER" 	NUMBER 		NOT NULL ENABLE, 
	"COLLEGE_BUILDING" 	NCHAR(50) 	NOT NULL ENABLE, 
	"CAPACITY" 			NUMBER 		NOT NULL ENABLE, 
	"CLASS_TYPE_ID" 	NUMBER 		NOT NULL ENABLE, 
	"CLASS_TYPE" 		NCHAR(20) 	NOT NULL ENABLE,  
	CONSTRAINT "CLASSROOM_PK" PRIMARY KEY ("CLUSSROOM_NUMBER", "COLLEGE_BUILDING") USING INDEX  ENABLE, 
	CONSTRAINT "CLASSROOM_CON" CHECK ( "CAPACITY" 			between 15 	and 200) ENABLE, 
	CONSTRAINT "NUMBER_LENGTH" CHECK ( "CLUSSROOM_NUMBER" 	between 100 and 999) ENABLE
   )
/

ALTER TABLE  "CLASSROOM" 
ADD CONSTRAINT "CLASSROOM_CLASS_TYPE_FK" 
FOREIGN KEY ("CLASS_TYPE_ID") 
REFERENCES  "CLASS_TYPE" ("ID") ENABLE
/


CREATE TABLE  "LECTURER" (	
    "ID" 	NUMBER 		NOT NULL ENABLE, 
	"NAME" 	NCHAR(100) 	NOT NULL ENABLE, 
	CONSTRAINT "LECTURER_PK" PRIMARY KEY ("NAME") USING INDEX  ENABLE
   )
/

CREATE INDEX index1 ON schema1.table1 (column1);
/

CREATE TABLE  "SUBJECT" (	
    "ID" 						NUMBER NOT NULL ENABLE, 
	"SUBJECT_NAME" 				NCHAR(50) NOT NULL ENABLE, 
	"LECTURER_ID" 				NUMBER NOT NULL ENABLE, 
	"LECTURER_NAME" 			NCHAR(50) NOT NULL ENABLE, 
	"TIME" 						DATE, 
	"SESSION_COUNT_PER_WEEK" 	NUMBER, 
	"STUDENTS_COUNT" 			NUMBER, 
	 CONSTRAINT "SUBJECT_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
   )
/

ALTER TABLE  "SUBJECT" 
ADD CONSTRAINT "SUBJECT_LECTURER_FK" 
FOREIGN KEY ("LECTURER_ID")
REFERENCES  "LECTURER" ("ID") ENABLE
/

CREATE TABLE  "TIME_LIME" (	
    "CLASSROOM_CLUSSROOM_NUMBER" 	NUMBER 		NOT NULL ENABLE, 
	"CLASSROOM_COLLEGE_BUILDING" 	NCHAR (50) 	NOT NULL ENABLE, 
	"SUBJECT_ID" 					NUMBER 		NOT NULL ENABLE, 
	"start" 						TIMESTAMP (6), 
	"end" 							TIMESTAMP (6), 
	"Date"							DATE,
	
	 CONSTRAINT "SUB_CLASS_PK" PRIMARY KEY ( "CLASSROOM_CLUSSROOM_NUMBER", "CLASSROOM_COLLEGE_BUILDING", "SUBJECT_ID" ) USING INDEX  ENABLE, 
	 CONSTRAINT "TIME_LIME_CON" CHECK ( "start"  	BETWEEN '08:15:00' AND '16:00:00') ENABLE, 
	 CONSTRAINT "SET_END_GATE" 	CHECK ( "end"  		BETWEEN '14:30:00' AND '21:50:00') ENABLE
   )
/

ALTER TABLE  "TIME_LIME" 
ADD CONSTRAINT "SUB_CLASS_CLASSROOM_FK" 
FOREIGN KEY ("CLASSROOM_CLUSSROOM_NUMBER", "CLASSROOM_COLLEGE_BUILDING")
REFERENCES  "CLASSROOM" ("CLUSSROOM_NUMBER", "COLLEGE_BUILDING") ENABLE
/

ALTER TABLE  "TIME_LIME" 
ADD CONSTRAINT "SUB_CLASS_SUBJECT_FK" 
FOREIGN KEY ("SUBJECT_ID")
REFERENCES  "SUBJECT" ("ID") ENABLE
/

CREATE TABLE  "TEST_SEQ" (
	"ID" 	NUMBER 		NOT NULL ENABLE, 
	"NAME" 	NCHAR (50) 	NOT NULL ENABLE, 
	 CONSTRAINT "TEST_SEQ_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
   )
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_TEST_SEQ" 
  before insert on "TEST_SEQ"               
  for each row  
	begin   
		if :NEW."ID" is null then 
			select "TEST".nextval into :NEW."ID" from sys.dual; 
		end if; 
	end; 
/

ALTER TRIGGER  "BI_TEST_SEQ" ENABLE
/

CREATE INDEX  "LECTURER_NAME_IDX" ON  "LECTURER" ("NAME")
/
